version: '3.8'

services:

  nginx: 
    image: nginx:latest
    container_name: gateway
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - back-tier

  backend-1: 
    build: .
    container_name: app-1
    restart: unless-stopped
    networks:
      - back-tier
    environment:
      - APP_NAME=APP_1

  backend-2:
    build: .
    container_name: app-2
    restart: unless-stopped
    networks:
      - back-tier
    environment:
      - APP_NAME=APP_2
  
  backend-3:
    build: .
    container_name: app-3
    restart: unless-stopped
    networks:
      - back-tier
    environment:
      - APP_NAME=APP_3

# Containers Network
networks:
  back-tier: {}